version: '3.8'
services:
  nginx:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./app/vendor:/var/www/html/vendor
      - ./app:/var/www/html:delegated
      # xdebug
      - ./dockerfiles/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
      - ./env:/etc/mysql/sql
      - ./dockerfiles/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/var/www/html
volumes:
  data:
