version: '3.8'
services:
  nginx:
    # image: shotaromatsuya/footle-nginx:latest
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    # image: shotaromatsuya/footle-php:latest
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./app/vendor:/var/www/html/vendor
      - ./app:/var/www/html:delegated
      # xdebug
      - ./dockerfiles/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  mysql:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile.mysql
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
      - ./env:/etc/mysql/sql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/var/www/html
  job:
    build:
      context: .
      dockerfile: aws/dockerfile.job
    volumes:
      - ./app/vendor:/var/www/html/vendor
      - ./app:/var/www/html:delegated
    stdin_open: true
    tty: true
volumes:
  data:
