FROM public.ecr.aws/docker/library/mysql:8.0.30

COPY dockerfiles/initdb.d/* /docker-entrypoint-initdb.d/
RUN chown -R mysql.mysql /var/lib/mysql
CMD mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
VOLUME ["/var/lib/mysql"]