FROM amazon/aws-for-fluent-bit:3.4.15

COPY ./aws/fluent-bit-custom.conf /fluent-bit/custom.conf
COPY ./aws/myparsers.conf /fluent-bit/myparsers.conf
COPY ./aws/stream_processor.conf /fluent-bit/stream_processor.conf

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime