FROM mysql:8.4.3

COPY dockerfiles/initdb.d/* /docker-entrypoint-initdb.d/
COPY env/* /etc/mysql/sql/

CMD ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--default-time-zone=Asia/Tokyo"]